application: tripfiles
version: production-02
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  
- url: /js
  static_dir: js

- url: /support
  static_dir: support
  
- url: /.*
  script: ./app/tripfiles/main.py